import type { Config } from "tailwindcss";

// Mirrors the BriefcaseOS visual language (see briefcaseos_visual_language/DESIGN.md)
// and the original Stitch mockups so the ported screens render identically.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        surface: "#f8f9ff",
        tertiary: "#005022",
        "surface-container": "#e5eeff",
        "tertiary-fixed-dim": "#79db8d",
        "outline-variant": "#c4c5d7",
        "primary-container": "#1d4ed8",
        "surface-dim": "#cbdbf5",
        primary: "#0037b0",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed-variant": "#005323",
        "tertiary-container": "#006b2f",
        "secondary-container": "#d5e0f8",
        "on-error-container": "#93000a",
        background: "#f8f9ff",
        "on-primary-fixed-variant": "#0039b5",
        error: "#ba1a1a",
        "secondary-fixed": "#d8e3fb",
        "inverse-surface": "#213145",
        outline: "#747686",
        "on-background": "#0b1c30",
        "on-surface-variant": "#434655",
        "surface-tint": "#2151da",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#95f8a7",
        "primary-fixed": "#dce1ff",
        "on-secondary-container": "#586377",
        "primary-fixed-dim": "#b7c4ff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d3e4fe",
        "on-secondary": "#ffffff",
        "on-surface": "#0b1c30",
        secondary: "#545f73",
        "on-primary-container": "#cad3ff",
        "surface-container-high": "#dce9ff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed-dim": "#bcc7de",
        "inverse-primary": "#b7c4ff",
        "on-tertiary-container": "#88ea9a",
        "on-tertiary-fixed": "#00210a",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#111c2d",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001551",
        "tertiary-fixed-dim-2": "#79db8d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1440px",
        xs: "4px",
        gutter: "20px",
        unit: "4px",
        md: "16px",
        lg: "24px",
        "sidebar-width": "260px",
        xl: "32px",
        sm: "8px",
      },
      fontFamily: {
        "code-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-sm": ["var(--font-hanken)", "sans-serif"],
        "display-lg": ["var(--font-hanken)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-hanken)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        sans: ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
